spring.application.name=NocturnaPerformance
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/nocturna
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/nocturna
##spring.datasource.username=root
#spring.datasource.password=admin
#spring.jpa.show-sql: true
spring.quartz.properties.org.quartz.threadPool.threadNamePrefix=nocturna-worker
spring.quartz.properties.org.quartz.threadPool.threadCount=2
nocturna.brand.loading=HOLLEY
nocturna.config.brand=TestingBrand

#2:30 am
cron.schedule.catalog=0 30 2 * * ?
cron.schedule.translate=0 30 3 * * ?
cron.schedule.export=0 30 4 * * ?
#brands https://api.pdm-automotive.com/api/v1/accounts/authorized_brands
##cron.schedule.brandcodes=BDDP
cron.schedule.brandcodes=FDDP
#Export builder plus report
cron.schedule.template=21941

#nocturna.site properties
nocturna.site.url=https://api.pdm-automotive.com/api/v1/products/export_builder_plus?template_id={template}&brand_code={brandCode}
nocturna.site.token=ANk55DO8mEptpNanZAWHGebZEfikECTW0QW33W7JSGCzqKvDPxGfy9u1qmgH98nC
nocturna.site.projectid=nocturnatesttranslate
nocturna.site.languaje=es

#shopify API urls
shopify.site.products=https://nocturna-dev-store.myshopify.com/admin/api/2025-01/products.json
shopify.site.token=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
