spring.application.name=NocturnaPerformance
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/nocturna
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/nocturna
##spring.datasource.username=root
#spring.datasource.password=admin
#spring.jpa.show-sql: true
spring.quartz.properties.org.quartz.threadPool.threadNamePrefix=nocturna-worker
spring.quartz.properties.org.quartz.threadPool.threadCount=2
nocturna.brand.loading=HOLLEY
nocturna.config.brand=TestingBrand