spring.application.name=NocturnaPerformance
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/nocturna
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.quartz.properties.org.quartz.threadPool.threadNamePrefix=nocturna-worker
spring.quartz.properties.org.quartz.threadPool.threadCount=2
nocturna.brand.loading=HOLLEY
nocturna.config.brand=TestingBrand

#2:30 am
cron.schedule.catalog=0 30 2 * * ?
cron.schedule.translate=0 30 3 * * ?
cron.schedule.export=0 30 4 * * ?
#brands https://api.pdm-automotive.com/api/v1/accounts/authorized_brands
cron.schedule.brandcodes=BDDP
##cron.schedule.brandcodes=FDDP
#Export builder plus report
cron.schedule.template=21941

#nocturna.site properties
holley.pdm.url=https://api.pdm-automotive.com/api/v1/products/export_builder_plus?template_id={template}&brand_code={brandCode}
holley.pdm.token=ANk55DO8mEptpNanZAWHGebZEfikECTW0QW33W7JSGCzqKvDPxGfy9u1qmgH98nC
holley.pdm.projectid=nocturnatesttranslate
holley.pdm.languaje=es
holley.pdm.template=21941

#shopify API urls
shopify.storeDomain=nocturna-dev-store.myshopify.com
shopify.accessToken=
shopify.apiVersion=2026-04
shopify.loadMetafields=true
shopify.createProducts=https://nocturna-dev-store.myshopify.com/admin/api/2026-04/products.json
