Authorization:
Key - API-Token
Value - ANk55DO8mEptpNanZAWHGebZEfikECTW0QW33W7JSGCzqKvDPxGfy9u1qmgH98nC
Add to - Header

GET - https://api.pdm-automotive.com/api/v1/products/export_builder_plus?template_id=21941&part_number=8401&limit=1&brand_code=BDDP