Pendientes
1. Hay productos con multiples categorias, hay que separar y crear una collection para cu de ellas
    1.1 revisar # categorias para ver si se hace manual o por codigo
2. consultar marcas, comparar con tabla, las nuevas se insertan y se envia correo con notificacion de nueva marca para completado de perfil manual
3. la traduccion falla si se manda cadena de texto vacia, validar texto para no agregar cadenas vacias
    3.1 - preguntar a copilot si no se le ocurre una manera de hacer que sea mas rapido y/o economico
4. determinar si creo una tabla para almacenar todo con traducciones, una tabla solo de upc y traducciones o alguna otra manera
    4.1 si o si se guardan las traducciones
5. codigo del metafield
6. codigo para crear colecciones
7. codigo para crear productos
8. probar buscador en shopify
    8.1 configurar metafields para que funcione la busqueda
